In [1]:
import torch

In [2]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones(3, 4, 3)

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [4]:
torch.Tensor([[1, 2, 3], [1, 2, 3]])

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [5]:
x = torch.Tensor([[1, 2, 3], [1, 2, 3]])

In [6]:
x.size()

torch.Size([2, 3])

In [7]:
x.shape

torch.Size([2, 3])

In [8]:
x.shape[0]

2

In [9]:
x[0]

tensor([1., 2., 3.])

In [10]:
x[0, 1]

tensor(2.)

In [11]:
x[:, 0:1]

tensor([[1.],
        [1.]])

In [12]:
x[0:1, :]

tensor([[1., 2., 3.]])

In [13]:
x[:, 0]

tensor([1., 1.])

In [14]:
x + 10

tensor([[11., 12., 13.],
        [11., 12., 13.]])

In [15]:
x ** 2

tensor([[1., 4., 9.],
        [1., 4., 9.]])

In [16]:
y = torch.Tensor([[2, 3, 4], [2, 3, 4]])

In [17]:
x + y

tensor([[3., 5., 7.],
        [3., 5., 7.]])

In [18]:
x * y

tensor([[ 2.,  6., 12.],
        [ 2.,  6., 12.]])

In [19]:
x / y

tensor([[0.5000, 0.6667, 0.7500],
        [0.5000, 0.6667, 0.7500]])

In [20]:
x // y

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x % y

tensor([[1., 2., 3.],
        [1., 2., 3.]])

In [22]:
torch.exp(x)

tensor([[ 2.7183,  7.3891, 20.0855],
        [ 2.7183,  7.3891, 20.0855]])

In [23]:
torch.log(x)

tensor([[0.0000, 0.6931, 1.0986],
        [0.0000, 0.6931, 1.0986]])

In [24]:
torch.sin(x)

tensor([[0.8415, 0.9093, 0.1411],
        [0.8415, 0.9093, 0.1411]])

In [25]:
x > 2

tensor([[False, False,  True],
        [False, False,  True]])

In [26]:
mask = x > 2
mask

tensor([[False, False,  True],
        [False, False,  True]])

In [27]:
x[mask]

tensor([3., 3.])

In [28]:
x[x > 2]

tensor([3., 3.])

In [29]:
X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(X[X > int(input())].sum())

7
tensor(17)


In [30]:
z = x
z[0, 0] = 999
print(z)
print(x)

tensor([[999.,   2.,   3.],
        [  1.,   2.,   3.]])
tensor([[999.,   2.,   3.],
        [  1.,   2.,   3.]])


In [31]:
x = torch.Tensor([[1,  2,  3,  4],
                  [5,  6,  7,  8],
                  [9, 10, 11, 12]])

In [32]:
y = x.clone()
y[0, 0] = 999
print(x)
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])


In [33]:
x.dtype

torch.float32

In [34]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [35]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [36]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [37]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [38]:
x = torch.rand([2000,3000])
x

tensor([[0.8220, 0.4933, 0.3832,  ..., 0.0940, 0.4711, 0.4090],
        [0.6436, 0.9227, 0.1957,  ..., 0.6928, 0.7469, 0.9752],
        [0.6168, 0.0922, 0.1658,  ..., 0.3326, 0.4348, 0.6140],
        ...,
        [0.5396, 0.7583, 0.0920,  ..., 0.5795, 0.6985, 0.9632],
        [0.1386, 0.9146, 0.0720,  ..., 0.4194, 0.8958, 0.2834],
        [0.7339, 0.3080, 0.1560,  ..., 0.9105, 0.4168, 0.5604]])

In [39]:
torch.cuda.is_available()

True

In [40]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [41]:
torch.device('cpu')

device(type='cpu')

In [42]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

In [43]:
x_cuda = x.to(device)
x_cuda

tensor([[0.8220, 0.4933, 0.3832,  ..., 0.0940, 0.4711, 0.4090],
        [0.6436, 0.9227, 0.1957,  ..., 0.6928, 0.7469, 0.9752],
        [0.6168, 0.0922, 0.1658,  ..., 0.3326, 0.4348, 0.6140],
        ...,
        [0.5396, 0.7583, 0.0920,  ..., 0.5795, 0.6985, 0.9632],
        [0.1386, 0.9146, 0.0720,  ..., 0.4194, 0.8958, 0.2834],
        [0.7339, 0.3080, 0.1560,  ..., 0.9105, 0.4168, 0.5604]],
       device='cuda:0')

In [44]:
%timeit y = (x - x + x * 10.0) ** 2

10.6 ms ± 438 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [45]:
%timeit y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

2.2 ms ± 855 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [46]:
%time y = (x - x + x * 10.0) ** 2

CPU times: user 44 ms, sys: 0 ns, total: 44 ms
Wall time: 11.3 ms


In [47]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0) ** 2

CPU times: user 227 µs, sys: 0 ns, total: 227 µs
Wall time: 233 µs
